CREATE DATABASE HOTEL;
USE HOTEL;
CREATE TABLE HUESPED(
	CI INT PRIMARY KEY NOT NULL,
    NOMBRE VARCHAR(60) NOT NULL,
    TELEFONO INT ,
    SEXO CHAR NOT NULL,
    EDAD TINYINT NOT NULL,
    NACIONALIDAD VARCHAR(30) NOT NULL
);

CREATE TABLE CARGO(
CODIGO INT NOT NULL PRIMARY KEY,
NOMBRE VARCHAR(60) NOT NULL,
SALARIO INT NOT NULL
);
CREATE TABLE PERSONA (
	CI INT PRIMARY KEY NOT NULL,
    NOMBRE VARCHAR(60) NOT NULL,
    NROCUENTA BIGINT, 
    CODIGOCARGO INT NOT NULL,
    FOREIGN KEY (CODIGOCARGO) REFERENCES CARGO(CODIGO)
		on update cascade
        on delete cascade
);

CREATE TABLE HORARIO (
	DIA VARCHAR(10) NOT NULL,
    HORAI DATETIME NOT NULL,
    HORAF DATETIME NOT NULL,
    CIPERSONA INT NOT NULL,
    FOREIGN KEY (CIPERSONA) REFERENCES PERSONA(CI)
		on update cascade
        on delete cascade
);
CREATE TABLE RESERVA(
	NRO INT PRIMARY KEY NOT NULL,
    FECHA DATE NOT NULL,
    DIAS_E tinyint ,
    MONTO FLOAT NOT NULL,
    CIHUESPED INT NOT NULL,
    CIPERSONAL INT NOT NULL,
    FOREIGN KEY  (CIHUESPED) REFERENCES HUESPED(CI)
		on update cascade
        on delete cascade,
    FOREIGN KEY (CIPERSONAL) REFERENCES PERSONA(CI)
		on update cascade
        on delete cascade
);

CREATE TABLE FACTURA(
	NROF INT PRIMARY KEY NOT NULL,
    FECHA DATE NOT NULL,
    NITH INT,
    NOMBREH VARCHAR(60),
    MONTO FLOAT NOT NULL,
    NRORESERVA INT NOT NULL,

    FOREIGN KEY (NRORESERVA) REFERENCES RESERVA(NRO)
		on update cascade
        on delete cascade
);

CREATE TABLE HABITACION(
	NRO INT PRIMARY KEY NOT NULL,
	PRECIO FLOAT  NOT NULL,
    ESTADO varchar(15) NOT NULL,
    NROPERSONA INT ,
    DESCRIPCION VARCHAR(100) 
);
CREATE TABLE ELIGE(
	NRORESERVA INT NOT NULL,
    NROHABITACION INT NOT NULL,
    primary key(NRORESERVA,NROHABITACION),
    foreign key (NRORESERVA) REFERENCES RESERVA(NRO)
		on update cascade
        on delete cascade,
    FOREIGN KEY (NROHABITACION) REFERENCES HABITACION(NRO)
		on update cascade
        on delete cascade    
);

