CREATE DATABASE MALLACURRICULAR;
USE MALLACURRICULAR;
CREATE TABLE MATERIA(
	SIGLA VARCHAR(6) PRIMARY KEY NOT NULL,
    NOMBRE VARCHAR(50) NOT NULL,
    SEMESTRE TINYINT NOT NULL # TINYINT VA DE 0 A 255
);
CREATE TABLE PREREQUISITO(
SIGLAMAT VARCHAR(6)   NOT NULL,
SIGLAPRE VARCHAR(6)   NOT NULL,
primary key(SIGLAMAT,SIGLAPRE),
FOREIGN KEY (SIGLAMAT) REFERENCES MATERIA(SIGLA)
	ON DELETE CASCADE 
    ON UPDATE CASCADE ,
FOREIGN KEY (SIGLAPRE) REFERENCES MATERIA(SIGLA)
	ON DELETE CASCADE 
    ON UPDATE CASCADE 
);

INSERT INTO MATERIA (SIGLA,NOMBRE,SEMESTRE) VALUES
('MAT101','CALCULO I',1),
('MAT119','ESTRUCTURAS DISCRETAS',1),
('INF110','INTRODUCCION A LA INFORMATICA',1),
('FIS100','FISICA I',1),
('LIN100','INGLES TECNICO I',1);

INSERT INTO MATERIA (SIGLA,NOMBRE,SEMESTRE) VALUES
('MAT102','CALCULO II',2),
('MAT103','ALGEBRA LINEAL',2),
('INF120','PROGRAMACION I',2),
('FIS102','FISICA II',2),
('LIN101','INGLES TECNICO II',2);

INSERT INTO PREREQUISITO  VALUES ('MAT102','MAT101');
INSERT INTO PREREQUISITO  VALUES ('MAT103','MAT119');
INSERT INTO PREREQUISITO  VALUES ('INF120','INF110');
INSERT INTO PREREQUISITO  VALUES ('FIS102','FIS100');
INSERT INTO PREREQUISITO  VALUES ('LIN101','LIN100');

INSERT INTO MATERIA (SIGLA, NOMBRE, SEMESTRE)  VALUES
('MAT207','ECUACIONES DIFERENCIALES',3),
('INF210','PROGRAMACION II',3),
('INF211','ARQUITECTURA DE COMPUTADORAS',3),
('FIS200','FISICA III',3),
('ADM100','ADMINISTRACION',3);

INSERT INTO PREREQUISITO VALUES ('MAT207','MAT102');
INSERT INTO PREREQUISITO VALUES ('INF210','MAT103');
INSERT INTO PREREQUISITO VALUES ('INF210','INF120');
INSERT INTO PREREQUISITO VALUES ('INF211','INF120');
INSERT INTO PREREQUISITO VALUES ('INF211','FIS102');
INSERT INTO PREREQUISITO VALUES ('FIS200','FIS102');
-- 4to semestre
INSERT INTO MATERIA VALUES('MAT202', 'PROBABILIDAD Y ESTADISTICA I', 4);
INSERT INTO MATERIA VALUES('MAT205', 'METODOS NUMERICOS', 4);
INSERT INTO MATERIA VALUES('INF220', 'ESTRUCTURA DE DATOS I', 4);
INSERT INTO MATERIA VALUES('INF221', 'PROGRAMACION ENSAMBLADOR', 4);
INSERT INTO MATERIA VALUES('ADM200', 'CONTABILIDAD', 4);

-- 5to semestre
INSERT INTO MATERIA VALUES('MAT302', 'PROBABILIDAD Y ESTADISTICA II', 5);
INSERT INTO MATERIA VALUES('INF310', 'ESTRUCTURA DE DATOS II', 5);
INSERT INTO MATERIA VALUES('ADM330', 'ORGANIZACION Y METODOS', 5);
INSERT INTO MATERIA VALUES('INF312', 'BASE DE DATOS I', 5);
INSERT INTO MATERIA VALUES('ECO300', 'ECONOMIA PARA LA GESTION', 5);
-- 6to semestre

INSERT INTO MATERIA VALUES('MAT329', 'INVESTIGACION OPERATIVA I', 6);
INSERT INTO MATERIA VALUES('INF323', 'SISTEMAS OPERATIVOS I', 6);
INSERT INTO MATERIA VALUES('ADM320', 'FINANZAS PARA LA EMPRESA', 6);
INSERT INTO MATERIA VALUES('INF342', 'SISTEMAS DE INFORMACION', 6);
INSERT INTO MATERIA VALUES('INF322', 'BASE DE DATOS II', 6);

-- 7mo semestre
INSERT INTO MATERIA VALUES('MAT419', 'INVESTIGACION OPERATIVA II', 7);
INSERT INTO MATERIA VALUES('INF433', 'REDES I', 7);
INSERT INTO MATERIA VALUES('INF413', 'SISTEMAS OPERATIVOS II', 7);
INSERT INTO MATERIA VALUES('INF432', 'SISTEMAS PARA EL SOPORTE A LA TOMA DE DECISIONES', 7);
INSERT INTO MATERIA VALUES('INF412', 'SISTEMAS DE INFORMACION II', 7);

-- 8vo semestre
INSERT INTO MATERIA VALUES('ECO449', 'PREPARACION Y EVALUACION DE PROYECTOS', 8);
INSERT INTO MATERIA VALUES('INF423', 'REDES II', 8);
INSERT INTO MATERIA VALUES('INF462', 'AUDITORIA INFORMATICA', 8);
INSERT INTO MATERIA VALUES('INF442', 'SISTEMAS DE INFORMACION GEOGRAFICA', 8);
INSERT INTO MATERIA VALUES('INF422', 'INGENIERIA DE SOFTWARE I', 8);

-- 9no semestre
INSERT INTO MATERIA VALUES('INF511', 'TALLER DE GRADO I', 9);
INSERT INTO MATERIA VALUES('INF512', 'INGENIERIA DE SOFTWARE II', 9);
INSERT INTO MATERIA VALUES('INF513', 'TECNOLOGIA WEB', 9);
INSERT INTO MATERIA VALUES('INF552', 'ARQUITECTURA DE SOFTWARE', 9);
-- 10mo semestre - MODALIDAD LICENCIATURA
INSERT INTO MATERIA VALUES('GRL001', 'MODALIDAD DE LICENCIATURA', 10);


-- 4to semestre 6
INSERT INTO PREREQUISITO VALUES('MAT202', 'MAT102');
INSERT INTO PREREQUISITO VALUES('MAT205', 'MAT207');
INSERT INTO PREREQUISITO VALUES('INF220', 'MAT101');
INSERT INTO PREREQUISITO VALUES('INF220', 'INF210');
INSERT INTO PREREQUISITO VALUES('INF221', 'INF211');
INSERT INTO PREREQUISITO VALUES('ADM200', 'ADM100');
-- 5to semestre 5
INSERT INTO PREREQUISITO VALUES('MAT302', 'MAT202');
INSERT INTO PREREQUISITO VALUES('INF310', 'INF220');
INSERT INTO PREREQUISITO VALUES('ADM330', 'ADM200');
INSERT INTO PREREQUISITO VALUES('INF312', 'INF220');
INSERT INTO PREREQUISITO VALUES('ECO300', 'ADM200');
-- 6to semestre 5
INSERT INTO PREREQUISITO VALUES('MAT329', 'MAT302');
INSERT INTO PREREQUISITO VALUES('INF323', 'INF310');
INSERT INTO PREREQUISITO VALUES('ADM320', 'ADM330');
INSERT INTO PREREQUISITO VALUES('INF342', 'INF312');
INSERT INTO PREREQUISITO VALUES('INF322', 'INF312');
-- 7mo semestre 7
INSERT INTO PREREQUISITO VALUES('MAT419', 'MAT329');
INSERT INTO PREREQUISITO VALUES('INF433', 'INF323');
INSERT INTO PREREQUISITO VALUES('INF413', 'INF323');
INSERT INTO PREREQUISITO VALUES('INF432', 'INF342');
INSERT INTO PREREQUISITO VALUES('INF432', 'INF322');
INSERT INTO PREREQUISITO VALUES('INF412', 'INF342');
INSERT INTO PREREQUISITO VALUES('INF412', 'INF322');
-- 8vo semestre 6
INSERT INTO PREREQUISITO VALUES('ECO449', 'MAT419');
INSERT INTO PREREQUISITO VALUES('INF423', 'INF433');
INSERT INTO PREREQUISITO VALUES('INF462', 'ADM320');
INSERT INTO PREREQUISITO VALUES('INF462', 'INF412');
INSERT INTO PREREQUISITO VALUES('INF442', 'INF412');
INSERT INTO PREREQUISITO VALUES('INF422', 'INF412');
-- 9no semestre 20
INSERT INTO PREREQUISITO VALUES('INF511', 'ECO449');
INSERT INTO PREREQUISITO VALUES('INF511', 'INF423');
INSERT INTO PREREQUISITO VALUES('INF511', 'INF462');
INSERT INTO PREREQUISITO VALUES('INF511', 'INF442');
INSERT INTO PREREQUISITO VALUES('INF511', 'INF422');

INSERT INTO PREREQUISITO VALUES('INF512', 'ECO449');
INSERT INTO PREREQUISITO VALUES('INF512', 'INF423');
INSERT INTO PREREQUISITO VALUES('INF512', 'INF462');
INSERT INTO PREREQUISITO VALUES('INF512', 'INF442');
INSERT INTO PREREQUISITO VALUES('INF512', 'INF422');
INSERT INTO PREREQUISITO VALUES('INF513', 'ECO449');
INSERT INTO PREREQUISITO VALUES('INF513', 'INF423');
INSERT INTO PREREQUISITO VALUES('INF513', 'INF462');
INSERT INTO PREREQUISITO VALUES('INF513', 'INF442');
INSERT INTO PREREQUISITO VALUES('INF513', 'INF422');

INSERT INTO PREREQUISITO VALUES('INF552', 'ECO449');
INSERT INTO PREREQUISITO VALUES('INF552', 'INF423');
INSERT INTO PREREQUISITO VALUES('INF552', 'INF462');
INSERT INTO PREREQUISITO VALUES('INF552', 'INF442');
INSERT INTO PREREQUISITO VALUES('INF552', 'INF422');

-- 10mo semestre Licenciatura 4
INSERT INTO PREREQUISITO VALUES('GRL001', 'INF511');
INSERT INTO PREREQUISITO VALUES('GRL001', 'INF512');
INSERT INTO PREREQUISITO VALUES('GRL001', 'INF513');
INSERT INTO PREREQUISITO VALUES('GRL001', 'INF552');

# completar------------------------------------------------------------


# mostrar las materias que son prerequisitos para llevar ARQUITECTURA DE COMPUTADORAS
select SIGLA, NOMBRE
from PREREQUISITO,MATERIA
where SIGLAPRE=SIGLA AND PREREQUISITO.SIGLAMAT='INF211';

SELECT MATERIAPRE.NOMBRE
FROM MATERIA MATERIAPRE, PREREQUISITO, MATERIA MATERIALLEVAR
WHERE MATERIALLEVAR.SIGLA=SIGLAMAT AND MATERIAPRE.SIGLA=SIGLAPRE AND MATERIALLEVAR.SIGLA='INF211';

SELECT *
FROM MATERIA
WHERE SIGLA IN (SELECT SIGLAPRE
				FROM PREREQUISITO
                WHERE SIGLAMAT='INF211');

#PARA QUE MATERIAS ES PREREQUISITO SISTEMAS DE INFORMACION 2
SELECT *
FROM MATERIA
WHERE SIGLA IN ( SELECT SIGLAMAT
				FROM PREREQUISITO
                WHERE SIGLAPRE ='INF412');
SELECT *
FROM MATERIA
WHERE SIGLA IN ( SELECT SIGLAMAT
				FROM PREREQUISITO
                WHERE SIGLAPRE IN ( SELECT SIGLA
									FROM MATERIA
                                    WHERE NOMBRE='SISTEMAS DE INFORMACION II'));
                                    
SELECT MATERIALLEVAR.NOMBRE
FROM MATERIA MATERIAPRE, PREREQUISITO,MATERIA MATERIALLEVAR  
WHERE MATERIAPRE.SIGLA=SIGLAPRE AND MATERIALLEVAR.SIGLA=SIGLAMAT AND MATERIAPRE.NOMBRE='SISTEMAS DE INFORMACION II';

-- MOSTRAR MATERIAS SIN PREREQUISITOS

SELECT * 
FROM MATERIA
WHERE SIGLA NOT IN (SELECT SIGLAMAT
					FROM PREREQUISITO);

SELECT COUNT(*)
FROM MATERIA;
SELECT *
FROM PREREQUISITO;